name: jdenticon_dart
description: This is the Dart/Flutter implementation of the Jdenticon project. Jdenticon is a quick and easy to use library for generating highly recognizable identicons using SVG.
version: 2.0.0
homepage: https://github.com/VergillR/jdenticon-dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  crypto: ^3.0.3
  meta: ^1.9.1
  
dev_dependencies:
  very_good_analysis: ^5.1.0
